name: Flask Application CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # services:
    #   postgres:
    #     image: postgres:12
    #     env:
    #       POSTGRES_DB: yourdbname
    #       POSTGRES_USER: youruser
    #       POSTGRES_PASSWORD: yourpassword
    #     ports:
    #       - 5432:5432
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget xvfb libxi6 libgconf-2-4
        sudo apt-get install -y google-chrome-stable

    - name: Install ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        CHROMEDRIVER_VERSION="124.0.6367.91"  # Specify a known working version
        curl --silent --show-error --location --fail --retry 3 --output /tmp/chromedriver_linux64.zip "https://storage.googleapis.com/chrome-for-testing-public/124.0.6367.91/linux64/chrome-headless-shell-linux64.zip"
        cd /tmp
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver
        chromedriver --version


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install selenium behave

    - name: Run Behave tests
      run: |
        behave --junit --junit-directory=behave-reports

    - name: Upload Behave reports
      uses: actions/upload-artifact@v2
      with:
        name: behave-reports
        path: behave-reports/
